=begin comment

RadioManager

This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.

The version of the OpenAPI document: 2.0
Contact: support@pluxbox.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package RadioManagerClient::Object::Broadcast;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;


use base ("Class::Accessor", "Class::Data::Inheritable");

#
#
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

RadioManager

This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.

The version of the OpenAPI document: 2.0
Contact: support@pluxbox.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {});
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new {
    my ($class, %args) = @_;

    my $self = bless {}, $class;

    $self->init(%args);

    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON {
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            my $_json_attribute = $self->attribute_map->{$_key};
            my $_type = $self->openapi_types->{$_key};
            my $_value = $self->{$_key};
            if ($_type =~ /^array\[(.+)\]$/i) { # array
                my $_subclass = $1;
                $_data->{$_json_attribute} =  [ map { $self->_to_json_primitives($_subclass, $_) } @$_value ];
            } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
                my $_subclass = $1;
                my %_hash = ();
                while (my($_key, $_element) = each %{$_value}) {
                    $_hash{$_key} = $self->_to_json_primitives($_subclass, $_element);
                }
                $_data->{$_json_attribute} = \%_hash;
            } elsif ( grep( /^$_type$/, ('int', 'double', 'string', 'boolean', 'DATE', 'DATE_TIME'))) {
                $_data->{$_json_attribute} = $self->_to_json_primitives($_type, $_value);
            } else {
                $_data->{$_json_attribute} = $_value;
            }
        }
    }

    return $_data;
}

# to_json non-array data
sub _to_json_primitives {
    my ($self, $type, $data) = @_;
    if ( grep( /^$type$/, ('int', 'double'))) {
        # https://metacpan.org/pod/JSON#simple-scalars
        # numify it, ensuring it will be dumped as a number
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        # https://metacpan.org/pod/JSON#simple-scalars
        # stringified
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        # https://metacpan.org/pod/JSON#JSON::true,-JSON::false,-JSON::null
        return $data ? \1 : \0;
    } elsif ($type eq 'DATE') {
        return undef unless defined $data;
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Eymd($optional_separator),-$dt-%3Emdy(...),-$dt-%3Edmy(...)
            return $data->ymd;
        }
        return $data .q();
    } elsif ($type eq 'DATE_TIME') {
        return undef unless defined $data;
        # the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Erfc3339
            return $data->rfc3339;
        }
        return $data .q();
    } else { # hash (model),  In this case, the TO_JSON of the $data object is executed
        return $data;
    }
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key};
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }

    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if (grep( /^$type$/ , ('DATE_TIME', 'DATE'))) {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double'))) {
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        return !!$data;
    } else { # hash(model)
        my $_instance = eval "RadioManagerClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}


__PACKAGE__->class_documentation({description => '',
                                  class => 'Broadcast',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'program_id' => {
        datatype => 'int',
        base_name => 'program_id',
        description => '',
        format => '',
        read_only => '',
            },
    'model_type_id' => {
        datatype => 'int',
        base_name => 'model_type_id',
        description => '',
        format => '',
        read_only => '',
            },
    'station_id' => {
        datatype => 'int',
        base_name => 'station_id',
        description => '',
        format => '',
        read_only => '',
            },
    'field_values' => {
        datatype => 'object',
        base_name => 'field_values',
        description => '',
        format => '',
        read_only => '',
            },
    'title' => {
        datatype => 'string',
        base_name => 'title',
        description => '',
        format => '',
        read_only => '',
            },
    'start' => {
        datatype => 'DATE_TIME',
        base_name => 'start',
        description => '',
        format => '',
        read_only => '',
            },
    'stop' => {
        datatype => 'DATE_TIME',
        base_name => 'stop',
        description => '',
        format => '',
        read_only => '',
            },
    'genre_id' => {
        datatype => 'int',
        base_name => 'genre_id',
        description => '',
        format => '',
        read_only => '',
            },
    'description' => {
        datatype => 'string',
        base_name => 'description',
        description => '',
        format => '',
        read_only => '',
            },
    'short_name' => {
        datatype => 'string',
        base_name => 'short_name',
        description => '',
        format => '',
        read_only => '',
            },
    'medium_name' => {
        datatype => 'string',
        base_name => 'medium_name',
        description => '',
        format => '',
        read_only => '',
            },
    'website' => {
        datatype => 'string',
        base_name => 'website',
        description => '',
        format => '',
        read_only => '',
            },
    'email' => {
        datatype => 'string',
        base_name => 'email',
        description => '',
        format => '',
        read_only => '',
            },
    'recommended' => {
        datatype => 'boolean',
        base_name => 'recommended',
        description => '',
        format => '',
        read_only => '',
            },
    'language' => {
        datatype => 'string',
        base_name => 'language',
        description => '',
        format => '',
        read_only => '',
            },
    'published' => {
        datatype => 'boolean',
        base_name => 'published',
        description => '',
        format => '',
        read_only => '',
            },
    'repetition_uid' => {
        datatype => 'string',
        base_name => 'repetition_uid',
        description => '',
        format => '',
        read_only => '',
            },
    'repetition_type' => {
        datatype => 'string',
        base_name => 'repetition_type',
        description => '',
        format => '',
        read_only => '',
            },
    'repetition_end' => {
        datatype => 'DATE_TIME',
        base_name => 'repetition_end',
        description => '',
        format => '',
        read_only => '',
            },
    'repetition_start' => {
        datatype => 'DATE_TIME',
        base_name => 'repetition_start',
        description => '',
        format => '',
        read_only => '',
            },
    'repetition_days' => {
        datatype => 'string',
        base_name => 'repetition_days',
        description => '',
        format => '',
        read_only => '',
            },
    'pty_code_id' => {
        datatype => 'int',
        base_name => 'pty_code_id',
        description => '',
        format => '',
        read_only => '',
            },
    'planned_in_epg' => {
        datatype => 'int',
        base_name => 'planned_in_epg',
        description => '',
        format => '',
        read_only => '',
            },
    'group_id' => {
        datatype => 'int',
        base_name => 'group_id',
        description => '',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'program_id' => 'int',
    'model_type_id' => 'int',
    'station_id' => 'int',
    'field_values' => 'object',
    'title' => 'string',
    'start' => 'DATE_TIME',
    'stop' => 'DATE_TIME',
    'genre_id' => 'int',
    'description' => 'string',
    'short_name' => 'string',
    'medium_name' => 'string',
    'website' => 'string',
    'email' => 'string',
    'recommended' => 'boolean',
    'language' => 'string',
    'published' => 'boolean',
    'repetition_uid' => 'string',
    'repetition_type' => 'string',
    'repetition_end' => 'DATE_TIME',
    'repetition_start' => 'DATE_TIME',
    'repetition_days' => 'string',
    'pty_code_id' => 'int',
    'planned_in_epg' => 'int',
    'group_id' => 'int'
} );

__PACKAGE__->attribute_map( {
    'program_id' => 'program_id',
    'model_type_id' => 'model_type_id',
    'station_id' => 'station_id',
    'field_values' => 'field_values',
    'title' => 'title',
    'start' => 'start',
    'stop' => 'stop',
    'genre_id' => 'genre_id',
    'description' => 'description',
    'short_name' => 'short_name',
    'medium_name' => 'medium_name',
    'website' => 'website',
    'email' => 'email',
    'recommended' => 'recommended',
    'language' => 'language',
    'published' => 'published',
    'repetition_uid' => 'repetition_uid',
    'repetition_type' => 'repetition_type',
    'repetition_end' => 'repetition_end',
    'repetition_start' => 'repetition_start',
    'repetition_days' => 'repetition_days',
    'pty_code_id' => 'pty_code_id',
    'planned_in_epg' => 'planned_in_epg',
    'group_id' => 'group_id'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
