=begin comment

RadioManager

RadioManager

OpenAPI spec version: 2.0
Contact: support@pluxbox.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package RadioManagerClient::Object::ItemResult;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

RadioManager

RadioManager

OpenAPI spec version: 2.0
Contact: support@pluxbox.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "RadioManagerClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'ItemResult',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
    	datatype => 'int',
    	base_name => 'id',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'updated_at' => {
    	datatype => 'DateTime',
    	base_name => 'updated_at',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'created_at' => {
    	datatype => 'DateTime',
    	base_name => 'created_at',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'deleted_at' => {
    	datatype => 'DateTime',
    	base_name => 'deleted_at',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'data_modified' => {
    	datatype => 'int',
    	base_name => 'data_modified',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'order' => {
    	datatype => 'int',
    	base_name => 'order',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'templateblock_id' => {
    	datatype => 'int',
    	base_name => 'templateblock_id',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'templateitem_id' => {
    	datatype => 'int',
    	base_name => 'templateitem_id',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    '_external_station_id' => {
    	datatype => 'int',
    	base_name => '_external_station_id',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'model_type_id' => {
    	datatype => 'int',
    	base_name => 'model_type_id',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'block_id' => {
    	datatype => 'int',
    	base_name => 'block_id',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'external_id' => {
    	datatype => 'string',
    	base_name => 'external_id',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'field_values' => {
    	datatype => 'object',
    	base_name => 'field_values',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'title' => {
    	datatype => 'string',
    	base_name => 'title',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'duration' => {
    	datatype => 'int',
    	base_name => 'duration',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'start' => {
    	datatype => 'DateTime',
    	base_name => 'start',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'status' => {
    	datatype => 'string',
    	base_name => 'status',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'import' => {
    	datatype => 'int',
    	base_name => 'import',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'campaign_id' => {
    	datatype => 'int',
    	base_name => 'campaign_id',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'recommended' => {
    	datatype => 'boolean',
    	base_name => 'recommended',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'station_draft_id' => {
    	datatype => 'int',
    	base_name => 'station_draft_id',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'program_draft_id' => {
    	datatype => 'int',
    	base_name => 'program_draft_id',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'user_draft_id' => {
    	datatype => 'int',
    	base_name => 'user_draft_id',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'static_start' => {
    	datatype => 'boolean',
    	base_name => 'static_start',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'details' => {
    	datatype => 'string',
    	base_name => 'details',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'block' => {
    	datatype => 'ItemRelationsBlock',
    	base_name => 'block',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'broadcast' => {
    	datatype => 'BlockRelationsBroadcast',
    	base_name => 'broadcast',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'program' => {
    	datatype => 'ItemRelationsProgram',
    	base_name => 'program',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'contacts' => {
    	datatype => 'ItemRelationsContacts',
    	base_name => 'contacts',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'tags' => {
    	datatype => 'ItemRelationsTags',
    	base_name => 'tags',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'campaign' => {
    	datatype => 'ItemRelationsCampaign',
    	base_name => 'campaign',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'model_type' => {
    	datatype => 'BroadcastRelationsModelType',
    	base_name => 'model_type',
    	description => '',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'id' => 'int',
    'updated_at' => 'DateTime',
    'created_at' => 'DateTime',
    'deleted_at' => 'DateTime',
    'data_modified' => 'int',
    'order' => 'int',
    'templateblock_id' => 'int',
    'templateitem_id' => 'int',
    '_external_station_id' => 'int',
    'model_type_id' => 'int',
    'block_id' => 'int',
    'external_id' => 'string',
    'field_values' => 'object',
    'title' => 'string',
    'duration' => 'int',
    'start' => 'DateTime',
    'status' => 'string',
    'import' => 'int',
    'campaign_id' => 'int',
    'recommended' => 'boolean',
    'station_draft_id' => 'int',
    'program_draft_id' => 'int',
    'user_draft_id' => 'int',
    'static_start' => 'boolean',
    'details' => 'string',
    'block' => 'ItemRelationsBlock',
    'broadcast' => 'BlockRelationsBroadcast',
    'program' => 'ItemRelationsProgram',
    'contacts' => 'ItemRelationsContacts',
    'tags' => 'ItemRelationsTags',
    'campaign' => 'ItemRelationsCampaign',
    'model_type' => 'BroadcastRelationsModelType'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'updated_at' => 'updated_at',
    'created_at' => 'created_at',
    'deleted_at' => 'deleted_at',
    'data_modified' => 'data_modified',
    'order' => 'order',
    'templateblock_id' => 'templateblock_id',
    'templateitem_id' => 'templateitem_id',
    '_external_station_id' => '_external_station_id',
    'model_type_id' => 'model_type_id',
    'block_id' => 'block_id',
    'external_id' => 'external_id',
    'field_values' => 'field_values',
    'title' => 'title',
    'duration' => 'duration',
    'start' => 'start',
    'status' => 'status',
    'import' => 'import',
    'campaign_id' => 'campaign_id',
    'recommended' => 'recommended',
    'station_draft_id' => 'station_draft_id',
    'program_draft_id' => 'program_draft_id',
    'user_draft_id' => 'user_draft_id',
    'static_start' => 'static_start',
    'details' => 'details',
    'block' => 'block',
    'broadcast' => 'broadcast',
    'program' => 'program',
    'contacts' => 'contacts',
    'tags' => 'tags',
    'campaign' => 'campaign',
    'model_type' => 'model_type'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
