=begin comment

RadioManager

RadioManager

OpenAPI spec version: 2.0
Contact: support@pluxbox.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package RadioManagerClient::Object::ModelTypeResult;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use RadioManagerClient::Object::ModelType;
use RadioManagerClient::Object::ModelTypeOptions;
use RadioManagerClient::Object::ModelTypeOutputOnly;
use RadioManagerClient::Object::ModelTypeRelations;
use RadioManagerClient::Object::ModelTypeRelationsBroadcasts;
use RadioManagerClient::Object::ModelTypeRelationsCampaigns;
use RadioManagerClient::Object::ModelTypeRelationsContacts;
use RadioManagerClient::Object::ModelTypeRelationsItems;
use RadioManagerClient::Object::ModelTypeRelationsPresenters;
use RadioManagerClient::Object::ModelTypeRelationsPrograms;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

RadioManager

RadioManager

OpenAPI spec version: 2.0
Contact: support@pluxbox.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "RadioManagerClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'ModelTypeResult',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
    	datatype => 'int',
    	base_name => 'id',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'name' => {
    	datatype => 'string',
    	base_name => 'name',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'model' => {
    	datatype => 'string',
    	base_name => 'model',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'created_at' => {
    	datatype => 'DateTime',
    	base_name => 'created_at',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'updated_at' => {
    	datatype => 'DateTime',
    	base_name => 'updated_at',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'options' => {
    	datatype => 'ModelTypeOptions',
    	base_name => 'options',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'order' => {
    	datatype => 'int',
    	base_name => 'order',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'deleted_at' => {
    	datatype => 'DateTime',
    	base_name => 'deleted_at',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'campaigns' => {
    	datatype => 'ModelTypeRelationsCampaigns',
    	base_name => 'campaigns',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'broadcasts' => {
    	datatype => 'ModelTypeRelationsBroadcasts',
    	base_name => 'broadcasts',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'programs' => {
    	datatype => 'ModelTypeRelationsPrograms',
    	base_name => 'programs',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'contacts' => {
    	datatype => 'ModelTypeRelationsContacts',
    	base_name => 'contacts',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'presenters' => {
    	datatype => 'ModelTypeRelationsPresenters',
    	base_name => 'presenters',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'items' => {
    	datatype => 'ModelTypeRelationsItems',
    	base_name => 'items',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    '_external_station_id' => {
    	datatype => 'int',
    	base_name => '_external_station_id',
    	description => '',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'id' => 'int',
    'name' => 'string',
    'model' => 'string',
    'created_at' => 'DateTime',
    'updated_at' => 'DateTime',
    'options' => 'ModelTypeOptions',
    'order' => 'int',
    'deleted_at' => 'DateTime',
    'campaigns' => 'ModelTypeRelationsCampaigns',
    'broadcasts' => 'ModelTypeRelationsBroadcasts',
    'programs' => 'ModelTypeRelationsPrograms',
    'contacts' => 'ModelTypeRelationsContacts',
    'presenters' => 'ModelTypeRelationsPresenters',
    'items' => 'ModelTypeRelationsItems',
    '_external_station_id' => 'int'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'name' => 'name',
    'model' => 'model',
    'created_at' => 'created_at',
    'updated_at' => 'updated_at',
    'options' => 'options',
    'order' => 'order',
    'deleted_at' => 'deleted_at',
    'campaigns' => 'campaigns',
    'broadcasts' => 'broadcasts',
    'programs' => 'programs',
    'contacts' => 'contacts',
    'presenters' => 'presenters',
    'items' => 'items',
    '_external_station_id' => '_external_station_id'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
