=begin comment

RadioManager

This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.

The version of the OpenAPI document: 2.0
Contact: support@pluxbox.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('RadioManagerClient::BlockApi');

my $api = RadioManagerClient::BlockApi->new();
isa_ok($api, 'RadioManagerClient::BlockApi');

#
# get_block_by_id test
#
# uncomment below and update the test
#my $get_block_by_id_id = undef; # replace NULL with a proper value
#my $get_block_by_id__external_station_id = undef; # replace NULL with a proper value
#my $get_block_by_id_result = $api->get_block_by_id(id => $get_block_by_id_id, _external_station_id => $get_block_by_id__external_station_id);

#
# get_current_block test
#
# uncomment below and update the test
#my $get_current_block_result = $api->get_current_block();

#
# get_next_block test
#
# uncomment below and update the test
#my $get_next_block_result = $api->get_next_block();

#
# list_blocks test
#
# uncomment below and update the test
#my $list_blocks_broadcast_id = undef; # replace NULL with a proper value
#my $list_blocks_item_id = undef; # replace NULL with a proper value
#my $list_blocks_program_id = undef; # replace NULL with a proper value
#my $list_blocks_start_min = undef; # replace NULL with a proper value
#my $list_blocks_start_max = undef; # replace NULL with a proper value
#my $list_blocks_page = undef; # replace NULL with a proper value
#my $list_blocks_limit = undef; # replace NULL with a proper value
#my $list_blocks_order_by = undef; # replace NULL with a proper value
#my $list_blocks_order_direction = undef; # replace NULL with a proper value
#my $list_blocks__external_station_id = undef; # replace NULL with a proper value
#my $list_blocks_result = $api->list_blocks(broadcast_id => $list_blocks_broadcast_id, item_id => $list_blocks_item_id, program_id => $list_blocks_program_id, start_min => $list_blocks_start_min, start_max => $list_blocks_start_max, page => $list_blocks_page, limit => $list_blocks_limit, order_by => $list_blocks_order_by, order_direction => $list_blocks_order_direction, _external_station_id => $list_blocks__external_station_id);

