=begin comment

RadioManager

RadioManager

The version of the OpenAPI document: 2.0
Contact: support@pluxbox.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('RadioManagerClient::BlockApi');

my $api = RadioManagerClient::BlockApi->new();
isa_ok($api, 'RadioManagerClient::BlockApi');

#
# get_block_by_id test
#
{
    my $id = undef; # replace NULL with a proper value
    my $_external_station_id = undef; # replace NULL with a proper value
    my $result = $api->get_block_by_id(id => $id, _external_station_id => $_external_station_id);
}

#
# get_current_block test
#
{
    my $result = $api->get_current_block();
}

#
# get_next_block test
#
{
    my $result = $api->get_next_block();
}

#
# list_blocks test
#
{
    my $page = undef; # replace NULL with a proper value
    my $broadcast_id = undef; # replace NULL with a proper value
    my $item_id = undef; # replace NULL with a proper value
    my $program_id = undef; # replace NULL with a proper value
    my $start_min = undef; # replace NULL with a proper value
    my $start_max = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $order_by = undef; # replace NULL with a proper value
    my $order_direction = undef; # replace NULL with a proper value
    my $_external_station_id = undef; # replace NULL with a proper value
    my $result = $api->list_blocks(page => $page, broadcast_id => $broadcast_id, item_id => $item_id, program_id => $program_id, start_min => $start_min, start_max => $start_max, limit => $limit, order_by => $order_by, order_direction => $order_direction, _external_station_id => $_external_station_id);
}


1;
