=begin comment

RadioManager

This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.

The version of the OpenAPI document: 2.0
Contact: support@pluxbox.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('RadioManagerClient::BroadcastApi');

my $api = RadioManagerClient::BroadcastApi->new();
isa_ok($api, 'RadioManagerClient::BroadcastApi');

#
# create_broadcast test
#
# uncomment below and update the test
#my $create_broadcast_broadcast_data_input = undef; # replace NULL with a proper value
#my $create_broadcast_result = $api->create_broadcast(broadcast_data_input => $create_broadcast_broadcast_data_input);

#
# delete_broadcast_by_id test
#
# uncomment below and update the test
#my $delete_broadcast_by_id_id = undef; # replace NULL with a proper value
#my $delete_broadcast_by_id_result = $api->delete_broadcast_by_id(id => $delete_broadcast_by_id_id);

#
# get_broadcast_by_id test
#
# uncomment below and update the test
#my $get_broadcast_by_id_id = undef; # replace NULL with a proper value
#my $get_broadcast_by_id__external_station_id = undef; # replace NULL with a proper value
#my $get_broadcast_by_id_result = $api->get_broadcast_by_id(id => $get_broadcast_by_id_id, _external_station_id => $get_broadcast_by_id__external_station_id);

#
# get_current_broadcast test
#
# uncomment below and update the test
#my $get_current_broadcast_withunpublished = undef; # replace NULL with a proper value
#my $get_current_broadcast_result = $api->get_current_broadcast(withunpublished => $get_current_broadcast_withunpublished);

#
# get_daily_epg test
#
# uncomment below and update the test
#my $get_daily_epg_date = undef; # replace NULL with a proper value
#my $get_daily_epg_withunpublished = undef; # replace NULL with a proper value
#my $get_daily_epg_result = $api->get_daily_epg(date => $get_daily_epg_date, withunpublished => $get_daily_epg_withunpublished);

#
# get_epgby_date test
#
# uncomment below and update the test
#my $get_epgby_date_date = undef; # replace NULL with a proper value
#my $get_epgby_date_withunpublished = undef; # replace NULL with a proper value
#my $get_epgby_date_result = $api->get_epgby_date(date => $get_epgby_date_date, withunpublished => $get_epgby_date_withunpublished);

#
# get_next_broadcast test
#
# uncomment below and update the test
#my $get_next_broadcast_withunpublished = undef; # replace NULL with a proper value
#my $get_next_broadcast_result = $api->get_next_broadcast(withunpublished => $get_next_broadcast_withunpublished);

#
# get_weekly_epg test
#
# uncomment below and update the test
#my $get_weekly_epg_date = undef; # replace NULL with a proper value
#my $get_weekly_epg_withunpublished = undef; # replace NULL with a proper value
#my $get_weekly_epg_result = $api->get_weekly_epg(date => $get_weekly_epg_date, withunpublished => $get_weekly_epg_withunpublished);

#
# list_broadcasts test
#
# uncomment below and update the test
#my $list_broadcasts_program_id = undef; # replace NULL with a proper value
#my $list_broadcasts_block_id = undef; # replace NULL with a proper value
#my $list_broadcasts_model_type_id = undef; # replace NULL with a proper value
#my $list_broadcasts_tag_id = undef; # replace NULL with a proper value
#my $list_broadcasts_presenter_id = undef; # replace NULL with a proper value
#my $list_broadcasts_genre_id = undef; # replace NULL with a proper value
#my $list_broadcasts_group_id = undef; # replace NULL with a proper value
#my $list_broadcasts_item_id = undef; # replace NULL with a proper value
#my $list_broadcasts_planned_in_epg = undef; # replace NULL with a proper value
#my $list_broadcasts_start_min = undef; # replace NULL with a proper value
#my $list_broadcasts_start_max = undef; # replace NULL with a proper value
#my $list_broadcasts_page = undef; # replace NULL with a proper value
#my $list_broadcasts_limit = undef; # replace NULL with a proper value
#my $list_broadcasts_order_by = undef; # replace NULL with a proper value
#my $list_broadcasts_order_direction = undef; # replace NULL with a proper value
#my $list_broadcasts__external_station_id = undef; # replace NULL with a proper value
#my $list_broadcasts_result = $api->list_broadcasts(program_id => $list_broadcasts_program_id, block_id => $list_broadcasts_block_id, model_type_id => $list_broadcasts_model_type_id, tag_id => $list_broadcasts_tag_id, presenter_id => $list_broadcasts_presenter_id, genre_id => $list_broadcasts_genre_id, group_id => $list_broadcasts_group_id, item_id => $list_broadcasts_item_id, planned_in_epg => $list_broadcasts_planned_in_epg, start_min => $list_broadcasts_start_min, start_max => $list_broadcasts_start_max, page => $list_broadcasts_page, limit => $list_broadcasts_limit, order_by => $list_broadcasts_order_by, order_direction => $list_broadcasts_order_direction, _external_station_id => $list_broadcasts__external_station_id);

#
# print_broadcast_by_id test
#
# uncomment below and update the test
#my $print_broadcast_by_id_id = undef; # replace NULL with a proper value
#my $print_broadcast_by_id_template_id = undef; # replace NULL with a proper value
#my $print_broadcast_by_id_result = $api->print_broadcast_by_id(id => $print_broadcast_by_id_id, template_id => $print_broadcast_by_id_template_id);

#
# update_broadcast_by_id test
#
# uncomment below and update the test
#my $update_broadcast_by_id_id = undef; # replace NULL with a proper value
#my $update_broadcast_by_id_broadcast_data_input = undef; # replace NULL with a proper value
#my $update_broadcast_by_id_result = $api->update_broadcast_by_id(id => $update_broadcast_by_id_id, broadcast_data_input => $update_broadcast_by_id_broadcast_data_input);

