=begin comment

RadioManager

RadioManager

OpenAPI spec version: 2.0
Contact: support@pluxbox.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('RadioManagerClient::CampaignApi');

my $api = RadioManagerClient::CampaignApi->new();
isa_ok($api, 'RadioManagerClient::CampaignApi');

#
# create_campaign test
#
{
    my $data = undef; # replace NULL with a proper value
    my $result = $api->create_campaign(data => $data);
}

#
# delete_campaign_by_id test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->delete_campaign_by_id(id => $id);
}

#
# get_campaign_by_id test
#
{
    my $id = undef; # replace NULL with a proper value
    my $_external_station_id = undef; # replace NULL with a proper value
    my $result = $api->get_campaign_by_id(id => $id, _external_station_id => $_external_station_id);
}

#
# list_campaigns test
#
{
    my $page = undef; # replace NULL with a proper value
    my $model_type_id = undef; # replace NULL with a proper value
    my $item_id = undef; # replace NULL with a proper value
    my $start_min = undef; # replace NULL with a proper value
    my $start_max = undef; # replace NULL with a proper value
    my $_external_station_id = undef; # replace NULL with a proper value
    my $result = $api->list_campaigns(page => $page, model_type_id => $model_type_id, item_id => $item_id, start_min => $start_min, start_max => $start_max, _external_station_id => $_external_station_id);
}

#
# update_campaign_by_id test
#
{
    my $id = undef; # replace NULL with a proper value
    my $data = undef; # replace NULL with a proper value
    my $result = $api->update_campaign_by_id(id => $id, data => $data);
}


1;
