=begin comment

RadioManager

RadioManager

The version of the OpenAPI document: 2.0
Contact: support@pluxbox.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('RadioManagerClient::ContactApi');

my $api = RadioManagerClient::ContactApi->new();
isa_ok($api, 'RadioManagerClient::ContactApi');

#
# create_contact test
#
{
    my $data = undef; # replace NULL with a proper value
    my $result = $api->create_contact(data => $data);
}

#
# delete_contact_by_id test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->delete_contact_by_id(id => $id);
}

#
# get_contact_by_id test
#
{
    my $id = undef; # replace NULL with a proper value
    my $_external_station_id = undef; # replace NULL with a proper value
    my $result = $api->get_contact_by_id(id => $id, _external_station_id => $_external_station_id);
}

#
# list_contacts test
#
{
    my $page = undef; # replace NULL with a proper value
    my $item_id = undef; # replace NULL with a proper value
    my $model_type_id = undef; # replace NULL with a proper value
    my $tag_id = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $order_by = undef; # replace NULL with a proper value
    my $order_direction = undef; # replace NULL with a proper value
    my $_external_station_id = undef; # replace NULL with a proper value
    my $result = $api->list_contacts(page => $page, item_id => $item_id, model_type_id => $model_type_id, tag_id => $tag_id, limit => $limit, order_by => $order_by, order_direction => $order_direction, _external_station_id => $_external_station_id);
}

#
# update_contact_by_id test
#
{
    my $id = undef; # replace NULL with a proper value
    my $data = undef; # replace NULL with a proper value
    my $result = $api->update_contact_by_id(id => $id, data => $data);
}


1;
