=begin comment

RadioManager

RadioManager

OpenAPI spec version: 2.0
Contact: support@pluxbox.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('RadioManagerClient::ExternalMessageApi');

my $api = RadioManagerClient::ExternalMessageApi->new();
isa_ok($api, 'RadioManagerClient::ExternalMessageApi');

#
# queue_external_message test
#
{
    my $message = undef; # replace NULL with a proper value
    my $result = $api->queue_external_message(message => $message);
}


1;
