=begin comment

RadioManager

This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.

The version of the OpenAPI document: 2.0
Contact: support@pluxbox.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('RadioManagerClient::ItemApi');

my $api = RadioManagerClient::ItemApi->new();
isa_ok($api, 'RadioManagerClient::ItemApi');

#
# create_item test
#
# uncomment below and update the test
#my $create_item_item_data_input = undef; # replace NULL with a proper value
#my $create_item_result = $api->create_item(item_data_input => $create_item_item_data_input);

#
# current_item_post_structure test
#
# uncomment below and update the test
#my $current_item_post_structure_import_item = undef; # replace NULL with a proper value
#my $current_item_post_structure_result = $api->current_item_post_structure(import_item => $current_item_post_structure_import_item);

#
# current_item_post_timing test
#
# uncomment below and update the test
#my $current_item_post_timing_import_item = undef; # replace NULL with a proper value
#my $current_item_post_timing_result = $api->current_item_post_timing(import_item => $current_item_post_timing_import_item);

#
# delete_item_by_id test
#
# uncomment below and update the test
#my $delete_item_by_id_id = undef; # replace NULL with a proper value
#my $delete_item_by_id_result = $api->delete_item_by_id(id => $delete_item_by_id_id);

#
# get_current_item test
#
# uncomment below and update the test
#my $get_current_item_lastplayed = undef; # replace NULL with a proper value
#my $get_current_item_result = $api->get_current_item(lastplayed => $get_current_item_lastplayed);

#
# get_item_by_id test
#
# uncomment below and update the test
#my $get_item_by_id_id = undef; # replace NULL with a proper value
#my $get_item_by_id__external_station_id = undef; # replace NULL with a proper value
#my $get_item_by_id_result = $api->get_item_by_id(id => $get_item_by_id_id, _external_station_id => $get_item_by_id__external_station_id);

#
# list_items test
#
# uncomment below and update the test
#my $list_items_block_id = undef; # replace NULL with a proper value
#my $list_items_broadcast_id = undef; # replace NULL with a proper value
#my $list_items_model_type_id = undef; # replace NULL with a proper value
#my $list_items_tag_id = undef; # replace NULL with a proper value
#my $list_items_campaign_id = undef; # replace NULL with a proper value
#my $list_items_contact_id = undef; # replace NULL with a proper value
#my $list_items_program_draft_id = undef; # replace NULL with a proper value
#my $list_items_user_draft_id = undef; # replace NULL with a proper value
#my $list_items_station_draft_id = undef; # replace NULL with a proper value
#my $list_items_program_id = undef; # replace NULL with a proper value
#my $list_items_external_id = undef; # replace NULL with a proper value
#my $list_items_duration_min = undef; # replace NULL with a proper value
#my $list_items_duration_max = undef; # replace NULL with a proper value
#my $list_items_status = undef; # replace NULL with a proper value
#my $list_items_start_min = undef; # replace NULL with a proper value
#my $list_items_start_max = undef; # replace NULL with a proper value
#my $list_items_page = undef; # replace NULL with a proper value
#my $list_items_limit = undef; # replace NULL with a proper value
#my $list_items_order_by = undef; # replace NULL with a proper value
#my $list_items_order_direction = undef; # replace NULL with a proper value
#my $list_items__external_station_id = undef; # replace NULL with a proper value
#my $list_items_result = $api->list_items(block_id => $list_items_block_id, broadcast_id => $list_items_broadcast_id, model_type_id => $list_items_model_type_id, tag_id => $list_items_tag_id, campaign_id => $list_items_campaign_id, contact_id => $list_items_contact_id, program_draft_id => $list_items_program_draft_id, user_draft_id => $list_items_user_draft_id, station_draft_id => $list_items_station_draft_id, program_id => $list_items_program_id, external_id => $list_items_external_id, duration_min => $list_items_duration_min, duration_max => $list_items_duration_max, status => $list_items_status, start_min => $list_items_start_min, start_max => $list_items_start_max, page => $list_items_page, limit => $list_items_limit, order_by => $list_items_order_by, order_direction => $list_items_order_direction, _external_station_id => $list_items__external_station_id);

#
# playlist_post_merge test
#
# uncomment below and update the test
#my $playlist_post_merge_playlist_merge_body = undef; # replace NULL with a proper value
#my $playlist_post_merge_result = $api->playlist_post_merge(playlist_merge_body => $playlist_post_merge_playlist_merge_body);

#
# playlist_post_structure test
#
# uncomment below and update the test
#my $playlist_post_structure_playlist_structure_body = undef; # replace NULL with a proper value
#my $playlist_post_structure_result = $api->playlist_post_structure(playlist_structure_body => $playlist_post_structure_playlist_structure_body);

#
# playlist_post_timing test
#
# uncomment below and update the test
#my $playlist_post_timing_playlist_timing_body = undef; # replace NULL with a proper value
#my $playlist_post_timing_result = $api->playlist_post_timing(playlist_timing_body => $playlist_post_timing_playlist_timing_body);

#
# stop_current_item test
#
# uncomment below and update the test
#my $stop_current_item_items_stopcurrent_body = undef; # replace NULL with a proper value
#my $stop_current_item_result = $api->stop_current_item(items_stopcurrent_body => $stop_current_item_items_stopcurrent_body);

#
# update_item_by_id test
#
# uncomment below and update the test
#my $update_item_by_id_id = undef; # replace NULL with a proper value
#my $update_item_by_id_item_data_input = undef; # replace NULL with a proper value
#my $update_item_by_id_result = $api->update_item_by_id(id => $update_item_by_id_id, item_data_input => $update_item_by_id_item_data_input);

