=begin comment

RadioManager

This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.

The version of the OpenAPI document: 2.0
Contact: support@pluxbox.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('RadioManagerClient::ProgramApi');

my $api = RadioManagerClient::ProgramApi->new();
isa_ok($api, 'RadioManagerClient::ProgramApi');

#
# create_program test
#
# uncomment below and update the test
#my $create_program_program_data_input = undef; # replace NULL with a proper value
#my $create_program_result = $api->create_program(program_data_input => $create_program_program_data_input);

#
# delete_program_by_id test
#
# uncomment below and update the test
#my $delete_program_by_id_id = undef; # replace NULL with a proper value
#my $delete_program_by_id_result = $api->delete_program_by_id(id => $delete_program_by_id_id);

#
# get_program_by_id test
#
# uncomment below and update the test
#my $get_program_by_id_id = undef; # replace NULL with a proper value
#my $get_program_by_id__external_station_id = undef; # replace NULL with a proper value
#my $get_program_by_id_result = $api->get_program_by_id(id => $get_program_by_id_id, _external_station_id => $get_program_by_id__external_station_id);

#
# list_programs test
#
# uncomment below and update the test
#my $list_programs_broadcast_id = undef; # replace NULL with a proper value
#my $list_programs_model_type_id = undef; # replace NULL with a proper value
#my $list_programs_tag_id = undef; # replace NULL with a proper value
#my $list_programs_presenter_id = undef; # replace NULL with a proper value
#my $list_programs_genre_id = undef; # replace NULL with a proper value
#my $list_programs_group_id = undef; # replace NULL with a proper value
#my $list_programs_block_id = undef; # replace NULL with a proper value
#my $list_programs_item_id = undef; # replace NULL with a proper value
#my $list_programs_disabled = undef; # replace NULL with a proper value
#my $list_programs_page = undef; # replace NULL with a proper value
#my $list_programs_limit = undef; # replace NULL with a proper value
#my $list_programs_order_by = undef; # replace NULL with a proper value
#my $list_programs_order_direction = undef; # replace NULL with a proper value
#my $list_programs__external_station_id = undef; # replace NULL with a proper value
#my $list_programs_result = $api->list_programs(broadcast_id => $list_programs_broadcast_id, model_type_id => $list_programs_model_type_id, tag_id => $list_programs_tag_id, presenter_id => $list_programs_presenter_id, genre_id => $list_programs_genre_id, group_id => $list_programs_group_id, block_id => $list_programs_block_id, item_id => $list_programs_item_id, disabled => $list_programs_disabled, page => $list_programs_page, limit => $list_programs_limit, order_by => $list_programs_order_by, order_direction => $list_programs_order_direction, _external_station_id => $list_programs__external_station_id);

#
# update_program_by_id test
#
# uncomment below and update the test
#my $update_program_by_id_id = undef; # replace NULL with a proper value
#my $update_program_by_id_program_data_input = undef; # replace NULL with a proper value
#my $update_program_by_id_result = $api->update_program_by_id(id => $update_program_by_id_id, program_data_input => $update_program_by_id_program_data_input);

