=begin comment

RadioManager

This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.

The version of the OpenAPI document: 2.0
Contact: support@pluxbox.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('RadioManagerClient::UserApi');

my $api = RadioManagerClient::UserApi->new();
isa_ok($api, 'RadioManagerClient::UserApi');

#
# delete_user_by_id test
#
# uncomment below and update the test
#my $delete_user_by_id_id = undef; # replace NULL with a proper value
#my $delete_user_by_id_result = $api->delete_user_by_id(id => $delete_user_by_id_id);

#
# get_user_by_id test
#
# uncomment below and update the test
#my $get_user_by_id_id = undef; # replace NULL with a proper value
#my $get_user_by_id_result = $api->get_user_by_id(id => $get_user_by_id_id);

#
# invite_user_by_mail test
#
# uncomment below and update the test
#my $invite_user_by_mail_invite_user_data = undef; # replace NULL with a proper value
#my $invite_user_by_mail_result = $api->invite_user_by_mail(invite_user_data => $invite_user_by_mail_invite_user_data);

#
# list_users test
#
# uncomment below and update the test
#my $list_users_role_id = undef; # replace NULL with a proper value
#my $list_users_group_id = undef; # replace NULL with a proper value
#my $list_users_page = undef; # replace NULL with a proper value
#my $list_users_limit = undef; # replace NULL with a proper value
#my $list_users_order_by = undef; # replace NULL with a proper value
#my $list_users_order_direction = undef; # replace NULL with a proper value
#my $list_users_result = $api->list_users(role_id => $list_users_role_id, group_id => $list_users_group_id, page => $list_users_page, limit => $list_users_limit, order_by => $list_users_order_by, order_direction => $list_users_order_direction);

